"""add_fbs_and_acts_tables

Revision ID: 042127317f47
Revises: 2af3e24a23f6
Create Date: 2026-06-11 12:46:26.678215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042127317f47'
down_revision: Union[str, Sequence[str], None] = '2af3e24a23f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fbs_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('uzum_order_id', sa.String(length=64), nullable=False),
    sa.Column('sku_title', sa.String(length=256), nullable=False),
    sa.Column('order_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='NEW', nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'uzum_order_id', name='uq_fbs_orders_tenant_order')
    )
    with op.batch_alter_table('fbs_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fbs_orders_telegram_id'), ['telegram_id'], unique=False)

    op.create_table('shipping_acts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('act_number', sa.String(length=64), nullable=False),
    sa.Column('total_items', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipping_acts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_acts_telegram_id'), ['telegram_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipping_acts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_acts_telegram_id'))

    op.drop_table('shipping_acts')
    with op.batch_alter_table('fbs_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fbs_orders_telegram_id'))

    op.drop_table('fbs_orders')
    # ### end Alembic commands ###
