"""init_enterprise_schema

Revision ID: 2af3e24a23f6
Revises: 
Create Date: 2026-06-11 00:19:49.423181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2af3e24a23f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_snapshots',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('available', sa.BigInteger(), nullable=False),
    sa.Column('pending', sa.BigInteger(), nullable=False),
    sa.Column('commissions', sa.BigInteger(), nullable=False),
    sa.Column('payments', sa.JSON(), nullable=True),
    sa.Column('has_data', sa.Boolean(), nullable=False),
    sa.Column('finance_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    with op.batch_alter_table('finance_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_snapshots_shop_id'), ['shop_id'], unique=False)

    op.create_table('invoices',
    sa.Column('number', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=True),
    sa.Column('full_price', sa.BigInteger(), nullable=True),
    sa.Column('accepted_price', sa.BigInteger(), nullable=True),
    sa.Column('number_orders', sa.Integer(), nullable=True),
    sa.Column('number_accepted_orders', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.BigInteger(), nullable=True),
    sa.Column('stock_title', sa.String(length=256), nullable=True),
    sa.Column('ettn_id', sa.String(length=128), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uzum_id', sa.BigInteger(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'uzum_id', name='uq_invoices_tenant_uzum')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_uzum_id'), ['uzum_id'], unique=False)

    op.create_table('orders',
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=True),
    sa.Column('scheme', sa.String(length=8), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('invoice_number', sa.BigInteger(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accept_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deliver_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_cancelled', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uzum_id', sa.BigInteger(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'uzum_id', name='uq_orders_tenant_uzum')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index('ix_orders_tenant_status', ['telegram_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_uzum_id'), ['uzum_id'], unique=False)

    op.create_table('payment_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('telegram_payment_charge_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='created', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    # Именованный констрейнт идемпотентности платежей (см. handlers/billing.py).
    sa.UniqueConstraint('telegram_payment_charge_id', name='uq_payment_logs_charge_id')
    )
    with op.batch_alter_table('payment_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_logs_telegram_id'), ['telegram_id'], unique=False)

    op.create_table('returns',
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('external_number', sa.String(length=128), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uzum_id', sa.BigInteger(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'uzum_id', name='uq_returns_tenant_uzum')
    )
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_returns_external_number'), ['external_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_uzum_id'), ['uzum_id'], unique=False)

    op.create_table('shop_managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('manager_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_telegram_id', 'manager_telegram_id', name='uq_shop_manager')
    )
    with op.batch_alter_table('shop_managers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_managers_manager_telegram_id'), ['manager_telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_managers_owner_telegram_id'), ['owner_telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_managers_shop_id'), ['shop_id'], unique=False)

    op.create_table('sku_barcodes',
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('sku_title', sa.String(length=512), nullable=True),
    sa.Column('sku_full_title', sa.String(length=512), nullable=True),
    sa.Column('product_title', sa.String(length=512), nullable=True),
    sa.Column('article', sa.String(length=128), nullable=True),
    sa.Column('seller_item_code', sa.String(length=128), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uzum_id', sa.BigInteger(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'uzum_id', name='uq_sku_barcodes_tenant_uzum')
    )
    with op.batch_alter_table('sku_barcodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sku_barcodes_article'), ['article'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_barcodes_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_barcodes_seller_item_code'), ['seller_item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_barcodes_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_barcodes_sku_title'), ['sku_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_barcodes_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_barcodes_uzum_id'), ['uzum_id'], unique=False)

    op.create_table('support_tickets',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_topic_id'), ['topic_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user_products',
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('sku_title', sa.String(length=512), nullable=True),
    sa.Column('current_price', sa.BigInteger(), nullable=True),
    sa.Column('fbo_stock', sa.Integer(), nullable=True),
    sa.Column('fbs_stock', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('purchase_price', sa.BigInteger(), nullable=True),
    sa.Column('article', sa.String(length=128), nullable=True),
    sa.Column('sku_root', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uzum_id', sa.BigInteger(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'uzum_id', name='uq_user_products_tenant_uzum')
    )
    with op.batch_alter_table('user_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_products_article'), ['article'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_products_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_products_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_products_sku_root'), ['sku_root'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_products_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_products_uzum_id'), ['uzum_id'], unique=False)

    op.create_table('user_shops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('uzum_shop_id', sa.BigInteger(), nullable=False),
    sa.Column('shop_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('uzum_token', sa.String(length=2048), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'uzum_shop_id', name='uq_user_shops_tg_shop')
    )
    with op.batch_alter_table('user_shops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_shops_telegram_id'), ['telegram_id'], unique=False)

    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('subscription_tier', sa.String(length=16), server_default='free', nullable=False),
    sa.Column('plan_name', sa.String(length=32), server_default='Бесплатный', nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('USER', 'MANAGER', 'ADMIN', 'ROOT', name='userrole'), server_default='USER', nullable=False),
    # sa.false() рендерится диалектно: 0 на SQLite, false на PostgreSQL
    # (автоген выдал sa.text('0') — на PG это невалидный DEFAULT для Boolean).
    sa.Column('is_banned', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('uzum_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('search_text', sa.String(length=512), nullable=False),
    sa.Column('comm_fbo', sa.Float(), nullable=False),
    sa.Column('comm_fbs', sa.Float(), nullable=False),
    sa.Column('is_kgt', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uzum_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uzum_categories_search_text'), ['search_text'], unique=False)

    op.create_table('barcodes',
    sa.Column('invoice_pk', sa.Integer(), nullable=False),
    sa.Column('order_uzum_id', sa.BigInteger(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=True),
    sa.Column('sku_title', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uzum_id', sa.BigInteger(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_pk'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'uzum_id', name='uq_barcodes_tenant_uzum')
    )
    with op.batch_alter_table('barcodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barcodes_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_barcodes_invoice_pk'), ['invoice_pk'], unique=False)
        batch_op.create_index('ix_barcodes_order_barcode', ['order_uzum_id', 'barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_barcodes_order_uzum_id'), ['order_uzum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_barcodes_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_barcodes_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_barcodes_uzum_id'), ['uzum_id'], unique=False)

    op.create_table('order_items',
    sa.Column('order_pk', sa.Integer(), nullable=False),
    sa.Column('order_uzum_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=True),
    sa.Column('sku_title', sa.String(length=512), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('product_title', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('seller_price', sa.BigInteger(), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uzum_id', sa.BigInteger(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['order_pk'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'uzum_id', name='uq_order_items_tenant_uzum')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_pk'), ['order_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_uzum_id'), ['order_uzum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_sku_title'), ['sku_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_uzum_id'), ['uzum_id'], unique=False)

    op.create_table('return_items',
    sa.Column('return_pk', sa.Integer(), nullable=False),
    sa.Column('return_uzum_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=True),
    sa.Column('sku_title', sa.String(length=512), nullable=True),
    sa.Column('product_title', sa.String(length=512), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('packed_amount', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.BigInteger(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uzum_id', sa.BigInteger(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['return_pk'], ['returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'uzum_id', name='uq_return_items_tenant_uzum')
    )
    with op.batch_alter_table('return_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_items_return_pk'), ['return_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_items_return_uzum_id'), ['return_uzum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_items_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_items_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_items_uzum_id'), ['uzum_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_items_uzum_id'))
        batch_op.drop_index(batch_op.f('ix_return_items_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_return_items_sku_id'))
        batch_op.drop_index(batch_op.f('ix_return_items_return_uzum_id'))
        batch_op.drop_index(batch_op.f('ix_return_items_return_pk'))

    op.drop_table('return_items')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_uzum_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_sku_title'))
        batch_op.drop_index(batch_op.f('ix_order_items_sku_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_uzum_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_pk'))
        batch_op.drop_index(batch_op.f('ix_order_items_barcode'))

    op.drop_table('order_items')
    with op.batch_alter_table('barcodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barcodes_uzum_id'))
        batch_op.drop_index(batch_op.f('ix_barcodes_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_barcodes_sku_id'))
        batch_op.drop_index(batch_op.f('ix_barcodes_order_uzum_id'))
        batch_op.drop_index('ix_barcodes_order_barcode')
        batch_op.drop_index(batch_op.f('ix_barcodes_invoice_pk'))
        batch_op.drop_index(batch_op.f('ix_barcodes_barcode'))

    op.drop_table('barcodes')
    with op.batch_alter_table('uzum_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uzum_categories_search_text'))

    op.drop_table('uzum_categories')
    op.drop_table('users')
    with op.batch_alter_table('user_shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_shops_telegram_id'))

    op.drop_table('user_shops')
    with op.batch_alter_table('user_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_products_uzum_id'))
        batch_op.drop_index(batch_op.f('ix_user_products_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_user_products_sku_root'))
        batch_op.drop_index(batch_op.f('ix_user_products_shop_id'))
        batch_op.drop_index(batch_op.f('ix_user_products_product_id'))
        batch_op.drop_index(batch_op.f('ix_user_products_category_id'))
        batch_op.drop_index(batch_op.f('ix_user_products_article'))

    op.drop_table('user_products')
    op.drop_table('system_settings')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_topic_id'))

    op.drop_table('support_tickets')
    with op.batch_alter_table('sku_barcodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sku_barcodes_uzum_id'))
        batch_op.drop_index(batch_op.f('ix_sku_barcodes_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_sku_barcodes_sku_title'))
        batch_op.drop_index(batch_op.f('ix_sku_barcodes_shop_id'))
        batch_op.drop_index(batch_op.f('ix_sku_barcodes_seller_item_code'))
        batch_op.drop_index(batch_op.f('ix_sku_barcodes_barcode'))
        batch_op.drop_index(batch_op.f('ix_sku_barcodes_article'))

    op.drop_table('sku_barcodes')
    with op.batch_alter_table('shop_managers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_managers_shop_id'))
        batch_op.drop_index(batch_op.f('ix_shop_managers_owner_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_shop_managers_manager_telegram_id'))

    op.drop_table('shop_managers')
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_returns_uzum_id'))
        batch_op.drop_index(batch_op.f('ix_returns_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_returns_status'))
        batch_op.drop_index(batch_op.f('ix_returns_shop_id'))
        batch_op.drop_index(batch_op.f('ix_returns_external_number'))

    op.drop_table('returns')
    with op.batch_alter_table('payment_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_logs_telegram_id'))

    op.drop_table('payment_logs')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_uzum_id'))
        batch_op.drop_index('ix_orders_tenant_status')
        batch_op.drop_index(batch_op.f('ix_orders_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_shop_id'))
        batch_op.drop_index(batch_op.f('ix_orders_invoice_number'))

    op.drop_table('orders')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_uzum_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_stock_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_number'))

    op.drop_table('invoices')
    with op.batch_alter_table('finance_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_snapshots_shop_id'))

    op.drop_table('finance_snapshots')
    # ### end Alembic commands ###
